//@ui5-bundle productsmanage/admin-books/Component-preload.js
sap.ui.predefine("productsmanage/admin-books/Component", ["sap/fe/core/AppComponent"],e=>e.extend("productsmanage.admin-books.Component",{metadata:{manifest:"json"}}));
sap.ui.require.preload({
	"productsmanage/admin-books/i18n/i18n.properties":'appTitle = Manage Books\nappSubTitle = CAP Sample Application\nappDescription = CAP Sample Application to Manage Books\n',
	"productsmanage/admin-books/i18n/i18n_de.properties":'appTitle = Verwalte B\\u00fccher\nappSubTitle = CAP Beispielanwendung\nappDescription = CAP Beispielanwendung zur Verwaltung von B\\u00fcchern\n',
	"productsmanage/admin-books/i18n/i18n_en.properties":'appTitle = Manage Books\nappSubTitle = CAP Sample Application\nappDescription = CAP Sample Application to Manage Books\n',
	"productsmanage/admin-books/manifest.json":'{"_version":"1.8.0","sap.app":{"id":"productsmanage.admin-books","type":"application","title":"{{appTitle}}","description":"{{appDescription}}","i18n":"i18n/i18n.properties","applicationVersion":{"version":"1.0.0"},"dataSources":{"AdminService":{"uri":"odata/v4/admin/","type":"OData","settings":{"odataVersion":"4.0"}}},"crossNavigation":{"inbounds":{"Books-manage":{"signature":{"parameters":{},"additionalParameters":"allowed"},"semanticObject":"Books","action":"manage","title":"{{appTitle}}","info":"{{appDescription}}","subTitle":"{{appSubTitle}}","icon":"sap-icon://course-book"}}}},"sap.ui5":{"dependencies":{"minUI5Version":"1.136.0","libs":{"sap.fe.templates":{}}},"models":{"i18n":{"type":"sap.ui.model.resource.ResourceModel","uri":"i18n/i18n.properties"},"":{"dataSource":"AdminService","settings":{"synchronizationMode":"None","operationMode":"Server","autoExpandSelect":true,"earlyRequests":true}}},"routing":{"routes":[{"pattern":":?query:","name":"BooksList","target":"BooksList"},{"pattern":"Books({key}):?query:","name":"BooksDetails","target":"BooksDetails"}],"targets":{"BooksList":{"type":"Component","id":"BooksList","name":"sap.fe.templates.ListReport","options":{"settings":{"entitySet":"Books","liveMode":true,"navigation":{"Books":{"detail":{"route":"BooksDetails"}}}}}},"BooksDetails":{"type":"Component","id":"BooksDetailsList","name":"sap.fe.templates.ObjectPage","options":{"settings":{"entitySet":"Books"}}}}},"contentDensities":{"compact":true,"cozy":true},"flexBundle":false},"sap.ui":{"technology":"UI5","deviceTypes":{"desktop":true,"phone":true,"tablet":true}},"sap.fiori":{"registrationIds":[],"archeType":"transactional"},"sap.cloud":{"public":true,"service":"productsmanage.service"}}'
});
//# sourceMappingURL=Component-preload.js.map
